In [2]:
import pandas as pd
df1 = pd.read_csv("student-scores.csv")
df = df1.copy()
df.head()

,id,total_score,part_time_job,math_score,history_score,physics_score,career_aspiration
0,1,90,True,3,3,3,Algebra
1,2,80,True,2,3,3,Indices
2,3,50,False,1,2,2,Indices
3,4,140,True,5,5,4,Algebra
4,5,120,True,4,3,5,Algebra

In [3]:
df.columns
df.drop(columns=['id'],axis=1, inplace=True)

In [4]:
df.head()

,total_score,part_time_job,math_score,history_score,physics_score,career_aspiration
0,90,True,3,3,3,Algebra
1,80,True,2,3,3,Indices
2,50,False,1,2,2,Indices
3,140,True,5,5,4,Algebra
4,120,True,4,3,5,Algebra

In [5]:
# from sklearn.preprocessing import LabelEncoder

# # Create a LabelEncoder object
# label_encoder = LabelEncoder()

# # Encode categorical columns using label encoder
# df['gender'] = label_encoder.fit_transform(df['gender'])
# df['part_time_job'] = label_encoder.fit_transform(df['part_time_job'])
# df['extracurricular_activities'] = label_encoder.fit_transform(df['extracurricular_activities'])
# df['career_aspiration'] = label_encoder.fit_transform(df['career_aspiration'])
# Define mapping dictionaries for categorical features

part_time_job_map = {False: 0, True: 1}

career_aspiration_map = {
        'Algebra': 0, 'Set': 1, 'Indices': 2
    }
# Apply mapping to the DataFrame

df['part_time_job'] = df['part_time_job'].map(part_time_job_map)

df['career_aspiration'] = df['career_aspiration'].map(career_aspiration_map)

In [6]:
df.head()

,total_score,part_time_job,math_score,history_score,physics_score,career_aspiration
0,90,1,3,3,3,0
1,80,1,2,3,3,2
2,50,0,1,2,2,2
3,140,1,5,5,4,0
4,120,1,4,3,5,0

In [7]:
df['career_aspiration'].unique()

array([0, 2, 1], dtype=int64)

In [8]:
df['career_aspiration'].value_counts()

career_aspiration
0    41
1    39
2    20
Name: count, dtype: int64

In [9]:
from imblearn.over_sampling import SMOTE

# Create SMOTE object
smote = SMOTE(random_state=42)

# Separate features and target variable
X = df.drop('career_aspiration', axis=1)
y = df['career_aspiration']

# Apply SMOTE to the data
X_resampled, y_resampled = smote.fit_resample(X, y)

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_resampled,y_resampled,test_size=0.2, random_state=42)

In [11]:
X_train.shape

(98, 5)

In [12]:
from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Fit the scaler to the training data and transform both training and testing data
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [13]:
X_train_scaled.shape

(98, 5)

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import warnings
warnings.filterwarnings("ignore")

# Define models
models = {
    "Logistic Regression": LogisticRegression(),
    "Support Vector Classifier": SVC(),
    "Random Forest Classifier": RandomForestClassifier(),
    "K Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree Classifier": DecisionTreeClassifier(),
    "Gaussian Naive Bayes": GaussianNB(),
    "AdaBoost Classifier": AdaBoostClassifier(),
    "Gradient Boosting Classifier": GradientBoostingClassifier(),
    "XGBoost Classifier": XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')
}

# Train and evaluate each model
for name, model in models.items():
    print("="*50)
    print("Model:", name)
    # Train the model
    model.fit(X_train_scaled, y_train)
    
    # Predict on test set
    y_pred = model.predict(X_test_scaled)
    
    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    classification_rep = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    
    # Print metrics
    print("Accuracy:", accuracy)
    print("Classification Report:\n", classification_rep)
    print("Confusion Matrix:\n", conf_matrix)

==================================================
Model: Logistic Regression
Accuracy: 0.88
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.82      0.90      0.86        10
           2       0.75      1.00      0.86         3

    accuracy                           0.88        25
   macro avg       0.86      0.91      0.87        25
weighted avg       0.90      0.88      0.88        25

Confusion Matrix:
 [[10  2  0]
 [ 0  9  1]
 [ 0  0  3]]
==================================================
Model: Support Vector Classifier
Accuracy: 0.84
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      0.80      0.80        10
           2       0.60      1.00      0.75         3

    accuracy                           0.84        25
   macro avg       0.80      0.88      0.82        25
weighted avg       0.87      0.84      0.85        25

Confusion Matrix:
 [[10  2  0]
 [ 0  8  2]
 [ 0  0  3]]
==================================================
Model: Random Forest Classifier
Accuracy: 0.88
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.82      0.90      0.86        10
           2       0.75      1.00      0.86         3

    accuracy                           0.88        25
   macro avg       0.86      0.91      0.87        25
weighted avg       0.90      0.88      0.88        25

Confusion Matrix:
 [[10  2  0]
 [ 0  9  1]
 [ 0  0  3]]
==================================================
Model: K Nearest Neighbors
Accuracy: 0.84
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.80      0.80      0.80        10
           2       0.60      1.00      0.75         3

    accuracy                           0.84        25
   macro avg       0.80      0.88      0.82        25
weighted avg       0.87      0.84      0.85        25

Confusion Matrix:
 [[10  2  0]
 [ 0  8  2]
 [ 0  0  3]]
==================================================
Model: Decision Tree Classifier
Accuracy: 0.92
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.83      1.00      0.91        10
           2       1.00      1.00      1.00         3

    accuracy                           0.92        25
   macro avg       0.94      0.94      0.94        25
weighted avg       0.93      0.92      0.92        25

Confusion Matrix:
 [[10  2  0]
 [ 0 10  0]
 [ 0  0  3]]
==================================================
Model: Gaussian Naive Bayes
Accuracy: 0.76
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.83      0.83        12
           1       0.75      0.60      0.67        10
           2       0.60      1.00      0.75         3

    accuracy                           0.76        25
   macro avg       0.73      0.81      0.75        25
weighted avg       0.77      0.76      0.76        25

Confusion Matrix:
 [[10  2  0]
 [ 2  6  2]
 [ 0  0  3]]
==================================================
Model: AdaBoost Classifier
Accuracy: 0.64
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.55      0.60      0.57        10
           2       0.00      0.00      0.00         3

    accuracy                           0.64        25
   macro avg       0.52      0.48      0.49        25
weighted avg       0.70      0.64      0.66        25

Confusion Matrix:
 [[10  2  0]
 [ 0  6  4]
 [ 0  3  0]]
==================================================
Model: Gradient Boosting Classifier
Accuracy: 0.88
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.82      0.90      0.86        10
           2       0.75      1.00      0.86         3

    accuracy                           0.88        25
   macro avg       0.86      0.91      0.87        25
weighted avg       0.90      0.88      0.88        25

Confusion Matrix:
 [[10  2  0]
 [ 0  9  1]
 [ 0  0  3]]
==================================================
Model: XGBoost Classifier
Accuracy: 0.88
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.82      0.90      0.86        10
           2       0.75      1.00      0.86         3

    accuracy                           0.88        25
   macro avg       0.86      0.91      0.87        25
weighted avg       0.90      0.88      0.88        25

Confusion Matrix:
 [[10  2  0]
 [ 0  9  1]
 [ 0  0  3]]

In [15]:
model = RandomForestClassifier()

model.fit(X_train_scaled, y_train)
# Predict on test set
y_pred = model.predict(X_test_scaled)

# Calculate metrics
print("Accuracy: ",accuracy_score(y_test, y_pred))
print("Report: ",classification_report(y_test, y_pred))
print("Confusion Matrix: ",confusion_matrix(y_test, y_pred))

Accuracy:  0.88
Report:                precision    recall  f1-score   support

           0       1.00      0.83      0.91        12
           1       0.82      0.90      0.86        10
           2       0.75      1.00      0.86         3

    accuracy                           0.88        25
   macro avg       0.86      0.91      0.87        25
weighted avg       0.90      0.88      0.88        25

Confusion Matrix:  [[10  2  0]
 [ 0  9  1]
 [ 0  0  3]]

In [16]:
# test 1
print("Actual Label :", y_test.iloc[10])
print("Model Prediction :",model.predict(X_test_scaled[10].reshape(1,-1))[0])
if y_test.iloc[10]==model.predict(X_test_scaled[10].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 1
Model Prediction : 2
not sure......

In [18]:
# test 2
print("Actual Label :", y_test.iloc[1])
print("Model Prediction :",model.predict(X_test_scaled[1].reshape(1,-1))[0])
if y_test.iloc[2]==model.predict(X_test_scaled[2].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 1
Model Prediction : 1
Wow! Model doing well.....

In [19]:
# test 2
print("Actual Label :", y_test.iloc[3])
print("Model Prediction :",model.predict(X_test_scaled[3].reshape(1,-1))[0])
if y_test.iloc[3]==model.predict(X_test_scaled[3].reshape(1,-1)):
    print("Wow! Model doing well.....")
else:
    print("not sure......")

Actual Label : 2
Model Prediction : 2
Wow! Model doing well.....

In [20]:
import pickle

# SAVE FILES
pickle.dump(scaler,open("Models/scaler.pkl",'wb'))
pickle.dump(model,open("Models/model.pkl",'wb'))

In [21]:

# Load the scaler, label encoder, and model
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))

In [23]:
import pickle
import numpy as np

# Load the scaler, label encoder, model, and class names
scaler = pickle.load(open("Models/scaler.pkl", 'rb'))
model = pickle.load(open("Models/model.pkl", 'rb'))
class_names = ['Algebra', 'Set', 'Indices']

def Recommendations( part_time_job,
                    math_score, history_score, physics_score,
                    total_score):
    
    # Encode categorical variables
    
    part_time_job_encoded = 1 if part_time_job else 0
   
    
    # Create feature array
    feature_array = np.array([[part_time_job_encoded,  math_score, history_score, physics_score,
                              total_score]])
    
    # Scale features
    scaled_features = scaler.transform(feature_array)
    
    # Predict using the model
    probabilities = model.predict_proba(scaled_features)
    
    # Get top five predicted classes along with their probabilities
    top_classes_idx = np.argsort(-probabilities[0])[:2]
    top_classes_names_probs = [(class_names[idx], probabilities[0][idx]) for idx in top_classes_idx]
    
    return top_classes_names_probs

In [24]:
# Example usage 1
final_recommendations = Recommendations(
                                        part_time_job=False,
                                        math_score=1,
                                        history_score=1,
                                        physics_score=1,

                                        total_score=30,)

print("Top recommended studies with probabilities:")
print("="*50)
for class_name, probability in final_recommendations:
    print(f"{class_name} with probability {probability}")

Top recommended studies with probabilities:
==================================================
Set with probability 0.6903174603174602
Indices with probability 0.30968253968253967